export const Data = [
  {
    id: "1",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-ben-mack-6775268-720x470.jpg",
  },
  {
    id: "2",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-engin-akyurt-2725675-720x470.jpg",
  },
  {
    id: "3",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-ben-mack-6775268-720x470.jpg",
  },
  {
    id: "4",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-max-vakhtbovych-6890413-720x470.jpg",
  },
  {
    id: "5",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-ben-mack-6775268-720x470.jpg",
  },
  {
    id: "6",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-la-miko-3754595-720x470.jpg",
  },
  {
    id: "7",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-ben-mack-6775268-720x470.jpg",
  },
  {
    id: "8",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/04/pexels-pixabay-271619-720x470.jpg",
  },
  {
    id: "9",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-ben-mack-6775268-720x470.jpg",
  },
  {
    id: "10",
    name: "Project Title",
    desc: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
    price: "300$",
    src: "https://demo.himaratheme.com/wp-content/uploads/2022/05/pexels-rachel-claire-4992451-720x470.jpg",
  },
];
